#!/bin/bash
# Wraps ip command
 
if [ $UID -eq 0 ]
then
        #echo ruta correcta en centos "Executing: /sbin/ip $@"
        /sbin/ip $@
else
        #echo "Executing: sudo /sbin/ip $@"
         /sbin/ip $@
fi
 
exit 0
